version: '3'
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php:8.2
    container_name: php_bee
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./runtime/log/app:/var/www/runtime/log/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/my-php.ini:ro
    networks:
      - app-network
    depends_on:
      - memcached

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: mysql_bee
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: bee
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_bee
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./runtime/log/nginx:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local